import type { PatchInfo } from "./parsePatch.js";
import type { PackageInfo } from "./inferPackage.js";
import type { RepoInfo } from "./resolveRepo.js";

export interface IssueContent {
  title: string;
  body: string;
}

const PATCHLIFT_URL = "https://github.com/turadg/patchlift";
const SUMMARY_PLACEHOLDER =
  "<!-- 🔺️🔺️🔺️ PLEASE REPLACE THIS BLOCK with a description of your problem, and any other relevant context 🔺️🔺️🔺️ -->";

export function buildIssue(
  patchInfo: PatchInfo,
  packageInfo: PackageInfo,
  _repoInfo: RepoInfo,
  options: {
    title?: string;
    summary?: string;
  } = {},
): IssueContent {
  const spec = `${packageInfo.name}@${packageInfo.version}`;
  const title = options.title ?? `Patch for ${spec}`;
  const summaryBlock = options.summary ?? SUMMARY_PLACEHOLDER;

  const body = `Hi! 👋

Firstly, thanks for your work on this project! 🙂

I've had to patch it locally for my use case, and I thought it would be helpful to share, in case it could be useful for others as well.

${summaryBlock}

Here is the diff against \`${spec}\`:

\`\`\`diff
${patchInfo.rawContent.trim()}
\`\`\`

<em>This issue body was [partially generated by patchlift](${PATCHLIFT_URL}).</em>`;

  return { title, body };
}
