import type { PatchInfo } from './parsePatch.js';
import type { PackageInfo } from './inferPackage.js';
import type { RepoInfo } from './resolveRepo.js';

export interface IssueContent {
  title: string;
  body: string;
}

export function buildIssue(
  patchInfo: PatchInfo,
  packageInfo: PackageInfo,
  repoInfo: RepoInfo,
  options: {
    title?: string;
    summary?: string;
  } = {},
): IssueContent {
  const title =
    options.title ??
    `Upstream patch from ${packageInfo.name}@${packageInfo.version}`;

  const changedFiles = patchInfo.files.length > 0
    ? patchInfo.files.map((f) => `- \`${f}\``).join('\n')
    : '_No files detected_';

  const summarySection = options.summary
    ? `## Summary\n\n${options.summary}\n\n`
    : '';

  const body = `${summarySection}## Patch Details

**Package:** \`${packageInfo.name}@${packageInfo.version}\`
**Repository:** [${repoInfo.full}](https://github.com/${repoInfo.full})

### Changed Files

${changedFiles}

### Statistics

- **Additions:** ${patchInfo.additions}
- **Deletions:** ${patchInfo.deletions}

### Patch

\`\`\`diff
${patchInfo.rawContent.trim()}
\`\`\`

---
_This issue was generated by [patchlift](https://github.com/turadg/patchlift)._`;

  return { title, body };
}
